sudo: false

language: elixir

elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.0

otp_release:
  - 18.3
  - 19.3
  - 20.2

matrix:
  exclude:
    - elixir: 1.6.0
      otp_release: 18.3

env:
  - MIX_ENV=test

script: mix coveralls.travis

